export const FIND_ITEM_DISTANCE = 30
export const MAX_DISTANCE = 1000

export const MAX_LOVE_POINT = 200
export const THRESHOLD_BEST = 200
export const THRESHOLD_BETTER = 100

export const WALKING_STOPPER_MILLISECONDS = 3000
export const GETTING_THIRSTY_MILLISECONDS = 15000
// 시연을 위해 100%
export const CHANCE_TO_GET_THIRSTY = 1