export const FIND_ITEM_DISTANCE = 30
export const MAX_DISTANCE = 1000

export const MAX_LOVE_POINT = 200
export const THRESHOLD_BEST = 200
export const THRESHOLD_BETTER = 100

export const HATCHING_MILLISECONDS = 1000
export const WALKING_STOPPER_MILLISECONDS = 3000
export const GET_THIRSTY_MILLISECONDS = 15000
export const DRINK_STOPPER_MILLISECONDS = 3000
export const DESIRE_ITEM_MILLISECONDS = 15000
export const HAPPY_STOPPER_MILLISECONDS = 2000
export const EVOLVE_STOPPER_MILLISECONDS = 3000
// 시연을 위해 100%
export const CHANCE_TO_GET_THIRSTY = 1

export const CHARACTER_STATE_DEFAULT = "DEFAULT"
export const CHARACTER_STATE_WALKING = "WALKING"
export const CHARACTER_STATE_DESIRING = "DESIRING"
export const CHARACTER_STATE_THIRSTY = "THIRSTY"
export const CHARACTER_STATE_EVOLVING = "EVOLVING"
export const CHARACTER_STATE_HAPPY = "HAPPY"

export const ITEM_STATE_ON = "ON"
export const ITEM_STATE_OFF = "OFF"